
version: '3.7'
services:
  postgres:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myhome_db

    ports:
      - '5432:5432'

    volumes:
      - ./data:/var/lib/postgresql/data


